spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: false
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: mentor-service
          uri: lb://mentor-service
          predicates:
            - Path=/mentors/**
        - id: skill-service
          uri: lb://skill-service
          predicates:
            - Path=/skills/**
        - id: session-service
          uri: lb://session-service
          predicates:
            - Path=/sessions/**
        - id: group-service
          uri: lb://group-service
          predicates:
            - Path=/groups/**
        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/reviews/**

# Swagger Aggregation using Discovery Locator paths
springdoc:
  swagger-ui:
    urls:
      - name: 🔐 AUTH-SERVICE
        url: /auth-service/v3/api-docs
      - name: 👤 USER-SERVICE
        url: /user-service/v3/api-docs
      - name: 👨‍🏫 MENTOR-SERVICE
        url: /mentor-service/v3/api-docs
      - name: 🛠️ SKILL-SERVICE
        url: /skill-service/v3/api-docs
      - name: 📅 SESSION-SERVICE
        url: /session-service/v3/api-docs
      - name: 👥 GROUP-SERVICE
        url: /group-service/v3/api-docs
      - name: 🌟 REVIEW-SERVICE
        url: /review-service/v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: SkillSyncSecretKey2026XyzAbc123SuperSecure!@#

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    health:
      show-details: always
