spring:
  datasource:
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:20}
  jpa:
    show-sql: false
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      timeout: 2000

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://eureka-server:8761/eureka/}
  instance:
    prefer-ip-address: true

management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://zipkin:9411/api/v2/spans}

logging:
  level:
    root: INFO
    com.skillsync: INFO
    org.hibernate.SQL: WARN
    org.springframework.web: INFO
    org.springframework.cloud: INFO
    org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker: ERROR
    org.springframework.cloud.loadbalancer.config.LoadBalancerCaffeineWarnLogger: ERROR
    org.springframework.cloud.loadbalancer.config.LoadBalancerCacheAutoConfiguration$LoadBalancerCaffeineWarnLogger: ERROR
