jwt:
  secret: SkillSyncSecretKey2026XyzAbc123SuperSecure!@#
  expiration: 86400000
  refresh-expiration: 604800000

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/skillsync_auth?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:mysql}:3306/skillsync_auth?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
